<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Indonesia | Culture Sea</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;700;800&family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        *{box-sizing:border-box;margin:0} body{font-family:Poppins,sans-serif;background:#071922;color:#f6fbfd}.indo-hero{min-height:72vh;padding:34px 7%;display:flex;align-items:end;background:linear-gradient(90deg,rgba(6,18,26,.88),rgba(6,18,26,.35)),url('/images/flags/indonesia-flag.png') center/cover fixed}.back{position:absolute;top:28px;color:#fff;text-decoration:none;padding:10px 17px;border:1px solid #ffffff70;border-radius:30px}.eyebrow{color:#ffcac4;letter-spacing:3px;text-transform:uppercase;font-size:12px}.indo-hero h1{font:800 clamp(60px,10vw,135px) 'Playfair Display',serif;line-height:.9;margin:15px 0}.indo-hero p{max-width:640px;line-height:1.8;color:#e5edf0}.content{max-width:1200px;margin:auto;padding:80px 5%}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:-45px;position:relative}.stat{padding:22px;border-radius:18px;background:#103040;border:1px solid #ffffff1e}.stat strong{display:block;color:#f2c14e;font-size:25px}.stat span{font-size:12px;color:#bcd0d8}.section{margin-top:70px}.section h2{font:700 42px 'Playfair Display',serif;margin-bottom:14px}.section>p{max-width:820px;color:#b9cad1;line-height:1.9}.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:26px}.card,.city-card{padding:25px;border-radius:20px;background:#0d2937;border:1px solid #ffffff16}.card .icon{font-size:32px}.card h3,.city-card h3{margin:12px 0 8px}.card p,.city-card p{font-size:13px;color:#b9cad1;line-height:1.8}.city-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:26px}.city-card{text-decoration:none;color:white;transition:.25s}.city-card:hover{transform:translateY(-6px);border-color:#f2c14e}.live{display:inline-flex;gap:7px;align-items:center;color:#a8dcef;font-size:12px;margin-top:12px}.dot{width:8px;height:8px;border-radius:50%;background:#45dc91;box-shadow:0 0 9px #45dc91}.enter-transition{position:fixed;inset:0;z-index:9999;display:flex;pointer-events:none;overflow:hidden}.enter-transition::before,.enter-transition::after{content:'';width:50%;height:100%;background:#cf1020;transition:transform .75s cubic-bezier(.76,0,.24,1)}.enter-transition::before{border-right:1px solid rgba(255,255,255,.3)}.enter-transition::after{border-left:1px solid rgba(255,255,255,.3)}.enter-transition.open::before{transform:translateX(-100%)}.enter-transition.open::after{transform:translateX(100%)}@media(max-width:800px){.stats,.facts,.city-grid{grid-template-columns:1fr 1fr}.indo-hero{padding:30px;min-height:60vh}}@media(max-width:520px){.stats,.facts,.city-grid{grid-template-columns:1fr}.content{padding:55px 20px}}
    </style>
</head>
<body><div class="enter-transition" id="enterTransition"></div>
    <header class="indo-hero"><a class="back" href="/">← Kembali</a><div><span class="eyebrow">Negara Kepulauan</span><h1>Indonesia</h1><p>Negara kepulauan terbesar di dunia, yang menyatukan ribuan pulau, ratusan kelompok etnis, bahasa, serta bentang alam dari pegunungan hingga laut tropis.</p></div></header>
    <main class="content">
        <div class="stats"><div class="stat"><strong id="population">Memuat…</strong><span>Populasi terbaru · World Bank</span></div><div class="stat"><strong>38</strong><span>Provinsi</span></div><div class="stat"><strong>17.000+</strong><span>Pulau</span></div><div class="stat"><strong>Jakarta</strong><span>Pusat pemerintahan</span></div></div>
        <section class="section"><h2>Identitas Negara</h2><p>Republik Indonesia beribu kota di Jakarta, berbahasa resmi Indonesia, dan menggunakan Rupiah (IDR). Merah dan putih pada bendera melambangkan keberanian dan kesucian.</p></section>
        <section class="section"><h2>Alam, Flora & Fauna</h2><div class="facts"><article class="card"><div class="icon">🌺</div><h3>Rafflesia arnoldii</h3><p>Salah satu flora ikonik Indonesia, dikenal sebagai bunga tunggal berukuran sangat besar.</p></article><article class="card"><div class="icon">🦎</div><h3>Komodo</h3><p>Kadal terbesar di dunia yang hidup alami di Nusa Tenggara Timur.</p></article><article class="card"><div class="icon">🦅</div><h3>Elang Jawa</h3><p>Burung pemangsa endemik Jawa yang menjadi inspirasi Garuda Pancasila.</p></article></div></section>
        <section class="section"><h2>Geografi & Penduduk</h2><p>Indonesia membentang di antara Samudra Hindia dan Pasifik, berada di Cincin Api Pasifik, dan memiliki bentang hutan hujan, gunung api, dataran tinggi, hingga terumbu karang. Masyarakatnya mencakup lebih dari seribu kelompok etnis dengan keragaman adat dan bahasa daerah.</p><div class="live"><span class="dot"></span><span id="updated">Data populasi diperbarui otomatis saat halaman dibuka.</span></div></section>
        <section class="section"><h2>Wilayah & Kota di Indonesia</h2><p>Pilih wilayah terlebih dahulu untuk melihat kota-kota utama, keberagaman masyarakat, dan kebudayaan yang hidup di dalamnya.</p><div class="city-grid">@foreach($regions as $slug => $region)<a class="city-card" href="{{ route('regions.show', $slug) }}"><span class="eyebrow">Wilayah Indonesia</span><h3>{{ $region['name'] }}</h3><p>{{ $region['description'] }}</p></a>@endforeach</div></section>
    </main>
    <script>
        requestAnimationFrame(() => document.getElementById('enterTransition').classList.add('open'));
        fetch('https://api.worldbank.org/v2/country/IDN/indicator/SP.POP.TOTL?format=json&per_page=5').then(r=>r.json()).then(data=>{const latest=data[1].find(item=>item.value);document.getElementById('population').textContent=new Intl.NumberFormat('id-ID').format(latest.value);document.getElementById('updated').textContent=`Populasi terbaru tersedia: ${latest.date} · Sumber World Bank.`}).catch(()=>document.getElementById('population').textContent='Data tidak tersedia');
    </script>
</body>
</html>
